// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240409205138_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería y Bricolaje"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 18, 2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("237ef94a-706a-4f52-8a34-5d00f1170e4e"),
                            Category = 1,
                            Description = "308L Rt29k577js8 No Frost Ix Inv",
                            Discount = 20,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/36/HEL2958SSG.jpg",
                            Name = "Heladera samsung",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("cc2a8ec5-9418-4be5-9c97-ac983c66320d"),
                            Category = 1,
                            Description = "LAvarropas automático WM-85VVC5S6P Inverter vivace 8.5 kg silver",
                            Discount = 10,
                            ImageUrl = "https://76338a6a.flyingcdn.com/44686-large_default/lg-lavarropas-autwm-85vvc5s6p-inverter-vivace-85kg-silver.jpg",
                            Name = "Lg lavarropas automático",
                            Price = 1285713m
                        },
                        new
                        {
                            ProductId = new Guid("aedd5d2d-d583-4eeb-9fd8-6e5890e81839"),
                            Category = 1,
                            Description = "Tostadora atma eléctrica toat-39dn",
                            Discount = 0,
                            ImageUrl = "https://76338a6a.flyingcdn.com/39415-large_default/atma-tostadora-electrica-toat-39dn.jpg",
                            Name = "Tostadora",
                            Price = 39999m
                        },
                        new
                        {
                            ProductId = new Guid("343c0ed9-979d-49a5-8d46-d2fa38a03f7b"),
                            Category = 1,
                            Description = "Batidora atma planetaria bp-at21rp roja",
                            Discount = 0,
                            ImageUrl = "https://76338a6a.flyingcdn.com/42304-large_default/atma-batidora-planetaria-bp-at21rp-roja.jpg",
                            Name = "Batidora planetaria",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("1f71c499-b664-4efd-a069-65bcb6aad26e"),
                            Category = 2,
                            Description = "Smart Tv 50 Pulgadas 4K Ultra Hd 50Pud7406/77 - PHILIPS",
                            Discount = 5,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/253/TEL5006PHI.jpg",
                            Name = "Smart Tv 50 pulgadas 4k",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("0c4c7650-0f50-40d3-b30b-ee4cae47e3a2"),
                            Category = 2,
                            Description = "PS5 SLIM Standard con lector CD/DVD 1TB + 1 Joystick Regalo",
                            Discount = 20,
                            ImageUrl = "https://images.fravega.com/f300/dd39a03cd136501e71f52ef06e09c861.jpg.webp",
                            Name = "Consola Sony PlayStation 5",
                            Price = 900000m
                        },
                        new
                        {
                            ProductId = new Guid("14c1ede8-3732-4a29-ba27-e29ab831e5f7"),
                            Category = 2,
                            Description = "Proyector Gadnic Surr 5500 Lúmenes Con Filtro HEPA HDMI x 2 USB x 2",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/5b68c007ab23568b5379ac7708999b9a.jpg.webp",
                            Name = "Proyector",
                            Price = 283179m
                        },
                        new
                        {
                            ProductId = new Guid("e073cc8c-c36b-4cb4-9b87-7e02625ad5b2"),
                            Category = 2,
                            Description = "Drone Gadnic Con Camara Dual 4K",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/60354c20fe3a7afd1b747439ee22d522.jpg.webp",
                            Name = "Drone",
                            Price = 594099m
                        },
                        new
                        {
                            ProductId = new Guid("7adf1251-218d-4373-b839-59084f988fff"),
                            Category = 3,
                            Description = "Reebok zapatillas mujer - Glide mujer ch. -Dk grey-green",
                            Discount = 5,
                            ImageUrl = "https://megasports.vteximg.com.br/arquivos/ids/224093-1000-1000/41104788055_0.jpg?v=638267497579500000",
                            Name = "Reebok zapatillas mujer",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("1a281d2d-e29b-40cf-be27-2e8b56ce51a8"),
                            Category = 3,
                            Description = "Mochila De Viaje Travel Tech Grande Amplia Compartimientos",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/eab6e93f47c2a4a5156964361abd6aa0.jpg.webp",
                            Name = "Mochila de viaje",
                            Price = 104500m
                        },
                        new
                        {
                            ProductId = new Guid("2636e6d8-bc3d-4d25-b894-562384ea774e"),
                            Category = 3,
                            Description = "Bolso Amayra Fit Cómodo Gimnasio Deportivo",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/c60063d66bd91a656af89bf3bf4e0694.jpg.webp",
                            Name = "Bolso deportivo",
                            Price = 30800m
                        },
                        new
                        {
                            ProductId = new Guid("70fb0497-b798-4dca-a8dc-21af4f1ce933"),
                            Category = 3,
                            Description = "Modelo de anteojos de sol para mujer XOLD de la marca RUSTY.",
                            Discount = 15,
                            ImageUrl = "https://static.wixstatic.com/media/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/617495_87ec75c8071244158aa28802dcdb8108~mv2.jpg",
                            Name = "Anteojos de sol",
                            Price = 89600m
                        },
                        new
                        {
                            ProductId = new Guid("6251346a-7024-4ee9-966f-8fe9bf00f2e7"),
                            Category = 4,
                            Description = "Lampara Colgante Led L2020 Dorado Moderno Deco Luz Desing",
                            Discount = 0,
                            ImageUrl = "https://http2.mlstatic.com/D_Q_NP_660955-MLA74649779983_022024-B.jpg",
                            Name = "Lampara colgante",
                            Price = 99999m
                        },
                        new
                        {
                            ProductId = new Guid("7fd770ac-3d16-41da-934c-e3cc1f78f3e6"),
                            Category = 4,
                            Description = "",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/9b2bee9b6b6518b60eb262be396c44fb.jpg.webp",
                            Name = "Juego de Sábanas 1 1/2 plaza Jurassic",
                            Price = 22590m
                        },
                        new
                        {
                            ProductId = new Guid("6a8ab38f-9e06-45bc-9c59-40ef26b49e94"),
                            Category = 4,
                            Description = "La almohada de Piero Cervical está hecha de espuma, mejorando la postura del cuello y hombros. Medida: 65 x 35 cm.",
                            Discount = 0,
                            ImageUrl = "https://images.fravega.com/f300/30df4745cef1263ea72604f24c3a3929.jpg.webp",
                            Name = "Almohada de espuma cervical",
                            Price = 14999m
                        },
                        new
                        {
                            ProductId = new Guid("fcc771c7-92a5-4838-8db3-9df46f21b3b1"),
                            Category = 4,
                            Description = "Espejo Nam de fibras naturales. Importado de Vietnam Diámetro: 60cm Espejo Diámetro: 19cm",
                            Discount = 10,
                            ImageUrl = "https://images.fravega.com/f300/6c2f4d2d61e3672653e9789598a83334.jpg.webp",
                            Name = "Espejo Nam 60cm",
                            Price = 66990m
                        },
                        new
                        {
                            ProductId = new Guid("9d6b3a6b-79f2-476d-9194-f3f372b77336"),
                            Category = 5,
                            Description = "Una fragancia cautivadora nacida de la fusióninesperada entre el dulzor de notas afrutadas, la exclusiva rosatecnológica de Mugler y un elegante collar amaderado.",
                            Discount = 25,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/8cafa0a86860701ec5138a548d16cdc2/a/n/angel-nova-edp-rechargable-100ml_1.webp",
                            Name = "Angel nova EDP 100ml",
                            Price = 286000m
                        },
                        new
                        {
                            ProductId = new Guid("8955a95f-22b6-4050-99da-4eefa0b76fc2"),
                            Category = 5,
                            Description = "La máscara de pestañas Lash Sensational Sky High de larga duración brinda un volumen completo y una longitud ilimitada.",
                            Discount = 0,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/d41ed5f2410977369e7cfa45777ef8e0/1/4/142943-a-lash-sensational-sky-high-washable-very-black_1.webp",
                            Name = "Lash sensational sky high washable - very black",
                            Price = 22659m
                        },
                        new
                        {
                            ProductId = new Guid("66271c6b-6dff-4675-a5c7-2061d2370691"),
                            Category = 5,
                            Description = "Perfume para un hombre que vive en el presente, moldeado por la energía de la modernidad. Imprevisible, sorprende con su originalidad.",
                            Discount = 0,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/1/119078-a-stronger-with-you-edt-100ml_2.webp",
                            Name = "Stronge with you EDT 100ml",
                            Price = 174900m
                        },
                        new
                        {
                            ProductId = new Guid("71789ef5-8752-4d05-a677-e250fbd8b9b8"),
                            Category = 5,
                            Description = "UV defender protector solar facil fuido FPS50+ 40g - claro.UV Defender Fluido es resiste al agua y al sudor, con textura fluida.",
                            Discount = 15,
                            ImageUrl = "https://d3cdlnm7te7ky2.cloudfront.net/media/mf_webp/jpg/media/catalog/product/cache/mtools/300x300/catalog/product//1/5/150122-a-uv-defender-protector-solar-facial-fluido-fps50-40g-claro.webp",
                            Name = "Protector solar facial",
                            Price = 16253m
                        },
                        new
                        {
                            ProductId = new Guid("7029e824-ccf9-4448-b8dd-4eaaa1c7f4ab"),
                            Category = 6,
                            Description = "Bicicleta Mountain Bike X 1.0 Rodado 29 Talle 20 Negro - NORDIC",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/104/BIC2922NRD.jpg",
                            Name = "Bicicleta mountain bike",
                            Price = 589999m
                        },
                        new
                        {
                            ProductId = new Guid("0c9c2ba8-8656-4ca4-8c79-cf385fbfad89"),
                            Category = 6,
                            Description = "Soga Saltar Crossfit/fitness Ranbak 737 Azul - RANBAK",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0048RAN.jpg",
                            Name = "Soga saltar crossfit",
                            Price = 7300m
                        },
                        new
                        {
                            ProductId = new Guid("e0419edd-7ea4-491e-af64-ee1b4ea4a56c"),
                            Category = 6,
                            Description = "Rueda Doble Para Abdominales Ranbak 730 - RANBAK",
                            Discount = 0,
                            ImageUrl = "https://www.megatone.net/images/Articulos/zoom2x/304/01/MKT0060RAN.jpg",
                            Name = "Rueda doble para abdominales",
                            Price = 15799m
                        },
                        new
                        {
                            ProductId = new Guid("016ebfd1-09b1-4d54-81f6-807fbd4cdab2"),
                            Category = 6,
                            Description = "Bote Inflable Explorer Pro 100 22699/0 - INTEX",
                            Discount = 10,
                            ImageUrl = "https://www.megatone.net/Images/Articulos/zoom2x/116/BOT6990ITX.jpg",
                            Name = "Bote inflable",
                            Price = 42999m
                        },
                        new
                        {
                            ProductId = new Guid("4d2895ea-a8db-4cc2-b7d4-71246b5788c2"),
                            Category = 7,
                            Description = "Dragon Ball Figura 10cm Articulado Flash Super Saiyan Broly",
                            Discount = 0,
                            ImageUrl = "https://wabro.vteximg.com.br/arquivos/ids/187554-320-320/3.jpg?v=638030021553570000",
                            Name = "Broly Dragon ball",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = new Guid("d3bb5ea6-f010-46bf-b40f-012be837b639"),
                            Category = 7,
                            Description = "Legends of Akedo Powerstorm Battle Giants combina 2 figuras de acción de gigantes de batalla.",
                            Discount = 0,
                            ImageUrl = "https://m.media-amazon.com/images/I/51EXTNFIrYL._AC_.jpg",
                            Name = "Legends of Akedo Powerstorm Battle Giants",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = new Guid("859457de-0934-47d3-a0bf-90d706af3b6e"),
                            Category = 7,
                            Description = "Hasbro Gaming Simon Juego de memoria electrónica portátil con luces y sonidos para niños de 8 años en adelante",
                            Discount = 0,
                            ImageUrl = "https://m.media-amazon.com/images/I/81P7iHZ+1lL._AC_UL320_.jpg",
                            Name = "Hasbro Gaming Simon Juego de memoria",
                            Price = 30820m
                        },
                        new
                        {
                            ProductId = new Guid("e24fc246-78a8-40e7-b5f8-34a50fa63174"),
                            Category = 7,
                            Description = "Bloques Magneticos Grandes Varias Formas y colores 42 Piezas MG23",
                            Discount = 15,
                            ImageUrl = "https://images.fravega.com/f300/59412558bc3aad5f4a7e9bcfea3dc30c.jpg.webp",
                            Name = "Bloques magnéticos",
                            Price = 50399m
                        },
                        new
                        {
                            ProductId = new Guid("d6c1f23f-036d-4ce7-a986-943be4b9ef08"),
                            Category = 8,
                            Description = "Ferrero Rocher – Chocolate Bombón – 8 Unidades",
                            Discount = 0,
                            ImageUrl = "https://www.argensend.com/wp-content/uploads/2021/09/D_NQ_NP_913338-MLA40945655566_022020-O.jpeg",
                            Name = "Ferrero rocher",
                            Price = 7000m
                        },
                        new
                        {
                            ProductId = new Guid("9ee42ffa-6904-4fbe-92f0-f3eca6974fd8"),
                            Category = 8,
                            Description = "ACEITE ORGANICO DE OLIVA 500CC MAELCA",
                            Discount = 10,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/09/7798241870102.jpg",
                            Name = "Aceite de oliva",
                            Price = 12350m
                        },
                        new
                        {
                            ProductId = new Guid("25e07683-9997-4e50-b8f5-af8e732bcf46"),
                            Category = 8,
                            Description = "Yogurt de coco sabor arandanos 170 g quimya. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2019/07/721450715893.jpg",
                            Name = "Yogurt de coco sabor arandanos",
                            Price = 2600m
                        },
                        new
                        {
                            ProductId = new Guid("dc76e0fd-894c-4e0d-95ca-60b3e38412ad"),
                            Category = 8,
                            Description = "Jugo de limón con jengible orgánico 500 cc Las brisas. Apto veganos",
                            Discount = 0,
                            ImageUrl = "https://biomarket.com.ar/wp-content/uploads/2023/01/BRIS54_1.jpg",
                            Name = "Jugo de limón con jengibre",
                            Price = 37930m
                        },
                        new
                        {
                            ProductId = new Guid("2ea3f6f5-cb0d-483c-9214-b409a763d1ff"),
                            Category = 9,
                            Description = "Faber castell lapices de colores super soft x 24 escritura artística.",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/FABER%20CASTELL/3388_medium.jpg",
                            Name = "Lapices de colores",
                            Price = 28500m
                        },
                        new
                        {
                            ProductId = new Guid("5f71dea5-6a77-49ed-98fe-8524401ec404"),
                            Category = 9,
                            Description = "Mooving agenda 14 x 20 Harry Potter Diaria - Espiralada",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/MOOVING/20080_medium.jpg",
                            Name = "Agenda",
                            Price = 25500m
                        },
                        new
                        {
                            ProductId = new Guid("dc8caf88-baef-4d1a-9a42-554555ede254"),
                            Category = 9,
                            Description = "Casio calculadora científica a bateria FX-82ms",
                            Discount = 20,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/CASIO/8484_medium.jpg",
                            Name = "Calculadora científica",
                            Price = 29400m
                        },
                        new
                        {
                            ProductId = new Guid("312d0630-56a1-416b-b5eb-f6adf146f6ef"),
                            Category = 9,
                            Description = "Sifap tempera sólida x 6 pastel arte",
                            Discount = 0,
                            ImageUrl = "https://www.heavenimagenes.com/heavencommerce/11de0e5d-73b3-4c32-910b-8483d00a7205/images/v2/SIFAP/7597_medium.jpg",
                            Name = "Tempera sólida",
                            Price = 12863m
                        },
                        new
                        {
                            ProductId = new Guid("8b5271e9-2f70-4ee4-9c28-56e555ed5b58"),
                            Category = 10,
                            Description = "Planta de exterior",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/1096-home_default/alegria-del-hogar.jpg",
                            Name = "Alegria del hogar",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = new Guid("2301517e-6261-41fa-a310-a65d9a167511"),
                            Category = 10,
                            Description = "Cordyline terminalis rubra",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/3334-large_default/cordyline-rubra-dracena-rubra-dracena-rubra.jpg",
                            Name = "Dracena rubra",
                            Price = 7900m
                        },
                        new
                        {
                            ProductId = new Guid("6f0f3971-55a8-462f-8fc6-30b5bc80ca3c"),
                            Category = 10,
                            Description = "Maceta de barro Clásica - Nº8",
                            Discount = 0,
                            ImageUrl = "https://www.viverodeluca.com.ar/1273-large_default/maceta-de-barro-cl%C3%A1sica.jpg",
                            Name = "Maceta de barro",
                            Price = 940m
                        },
                        new
                        {
                            ProductId = new Guid("a45b70c9-9fdf-45f2-b145-81ecb2f2cbe3"),
                            Category = 10,
                            Description = "Desmalezadora Gamma Naftera 44Cc G1835ar - GAMMA",
                            Discount = 15,
                            ImageUrl = "https://www.megatone.net/images//Articulos/zoom2x/106/MKT0013GAM-1.jpg",
                            Name = "Desmalezadora",
                            Price = 242500m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal( 18, 2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal( 18, 2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal( 18, 2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal( 18, 2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal( 18, 2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryName")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryName");
                });

            modelBuilder.Entity("Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProductName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "SaleName")
                        .WithMany("SaleProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductName");

                    b.Navigation("SaleName");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
